name: Backend

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        defaults:
            run:
                working-directory: ./back-end-app
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Manage NPM Dependencies
              uses: ./.github/actions/cache-node-dependencies
              with:
                  # Pasamos otros valores, en este caso para el backend
                  app-name: "nest-app"
                  working-directory: "./back-end-app"
            - name: Build
              run: npm run build
